2018-04-14 08:54:16,043 - ERROR - 1. 接口编号 : 2.0 | 接口名称 : Space - 热门空间名 
2018-04-14 08:54:16,044 - ERROR - 2. 返回信息 ：预期返回={'names': ['舌尖上的中国', '美食', '民以食为天', '厨艺秀', '茶', '吃货世界', '正宗东海海鲜《海鲜大礼》', '吃货的世界', '我的衣柜', '我的店铺'], 'success': True} | 实际返回={'names': ['舌尖上的中国', '美食', '民以食为天', '茶', '吃货世界', '厨艺秀', '吃货的世界', '正宗东海海鲜《海鲜大礼》', '我的衣柜', '我的店铺'], 'success': True}
2018-04-14 08:54:16,044 - ERROR - 3. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 203, in test_api
    assert api_hope == response
AssertionError

2018-04-14 08:54:35,828 - ERROR - 1. 接口编号 : 2.0 | 接口名称 : Space - 热门空间名 
2018-04-14 08:54:35,829 - ERROR - 2. 返回信息 ：预期返回={'names': ['舌尖上的中国', '美食', '民以食为天', '厨艺秀', '茶', '吃货世界', '正宗东海海鲜《海鲜大礼》', '吃货的世界', '我的衣柜', '我的店铺'], 'success': True} | 实际返回={'names': ['舌尖上的中国', '美食', '民以食为天', '茶', '吃货世界', '厨艺秀', '吃货的世界', '正宗东海海鲜《海鲜大礼》', '我的衣柜', '我的店铺'], 'success': True}
2018-04-14 08:54:35,829 - ERROR - 3. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 203, in test_api
    assert api_hope == response
AssertionError

2018-04-14 09:45:09,224 - ERROR - 1. 接口编号 : 2.0 | 接口名称 : Space - 热门空间名 
2018-04-14 09:45:09,225 - ERROR - 2. 返回信息 ：预期返回={'names': ['舌尖上的中国', '美食', '民以食为天', '厨艺秀', '茶', '吃货世界', '正宗东海海鲜《海鲜大礼》', '吃货的世界', '我的衣柜', '我的店铺'], 'success': True} | 实际返回={'names': ['舌尖上的中国', '美食', '民以食为天', '茶', '吃货世界', '厨艺秀', '吃货的世界', '正宗东海海鲜《海鲜大礼》', '我的衣柜', '我的店铺'], 'success': True}
2018-04-14 09:45:09,225 - ERROR - 3. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 202, in test_api
    assert api_hope == response
AssertionError

2018-04-14 09:45:09,790 - ERROR - 1. 接口编号 : 4_1 | 接口名称 : Space - 空间列表 
2018-04-14 09:45:09,790 - ERROR - 2. 检查信息 : 测试机构=[3][name] | 实际返回结果:1111点 
2018-04-14 09:45:09,790 - ERROR - 3. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 178, in test_api
    assert False != api_check_result[0]
AssertionError

2018-04-14 09:46:16,414 - ERROR - 1. 接口编号 : 2.0 | 接口名称 : Space - 热门空间名 
2018-04-14 09:46:16,414 - ERROR - 2. 返回信息 ：预期返回={'names': ['舌尖上的中国', '美食', '民以食为天', '厨艺秀', '茶', '吃货世界', '正宗东海海鲜《海鲜大礼》', '吃货的世界', '我的衣柜', '我的店铺'], 'success': True} | 实际返回={'names': ['舌尖上的中国', '美食', '民以食为天', '茶', '厨艺秀', '吃货世界', '吃货的世界', '正宗东海海鲜《海鲜大礼》', '我的衣柜', '我的店铺'], 'success': True}
2018-04-14 09:46:16,415 - ERROR - 3. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 202, in test_api
    assert api_hope == response
AssertionError

2018-04-14 09:46:16,997 - ERROR - 1. 接口编号 : 4_1 | 接口名称 : Space - 空间列表 
2018-04-14 09:46:16,997 - ERROR - 2. 检查信息 : 测试机构=[3][name] | 实际返回结果:1111点 
2018-04-14 09:46:16,998 - ERROR - 3. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 178, in test_api
    assert False != api_check_result[0]
AssertionError

